"""Flow-of-Action prompt templates, adapted from the paper appendix (B.1, Fig. 10).

Adaptations for the offline benchmark:
  - Kubernetes alert/${alert_info} -> the benchmark instruction + incident window
    + the dataset background (basic_prompt schema).
  - Root-cause definition uses each dataset's closed answer_candidates / reasons
    vocab instead of pod/-0/-1/-2 naming; OpenRCA additionally requires the
    occurrence datetime (minute precision) since the benchmark scores it.
  - Historical-incident block removed from ObAgent (no historical KB).
  - K8s data tools mapped to our offline CSV tools.
"""
from __future__ import annotations

from typing import Dict, List


FLOW_ACTIONS = [
    "match_sop",
    "generate_sop",
    "generate_sop_code",
    "run_sop",
    "match_observation",
    "Speak",
]

DATA_TOOL_ACTIONS = [
    "whether_is_abnormal_metric",
    "get_relevant_metric",
    "collect_trace",
    "get_logs",
    "component_analyze",
]

# MainAgent may choose only flow actions. Data-analysis tools are available only
# inside generated SOP code, so the run follows the SOP workflow instead of
# bypassing it with ad hoc direct tool calls.
ALL_ACTIONS = FLOW_ACTIONS

# Signatures used by the legacy direct-tool dispatch path; MainAgent no longer
# sees these tools as actions, but SOP code can still call the underlying tools.
TOOL_SIGNATURES = {
    "whether_is_abnormal_metric": "whether_is_abnormal_metric(start_time, end_time, kpi_name, component=None)",
    "get_relevant_metric": "get_relevant_metric(query)",
    "collect_trace": "collect_trace(start_time, end_time, service=None)",
    "get_logs": "get_logs(component, start_time, end_time)",
    "component_analyze": "component_analyze(start_time, end_time)",
}


FLOW_RULES = """# SOP FLOW (hard workflow for choosing the next action)
- If at the beginning and there is no last action: next action should be match_sop (query = the fault information).
- If last action == match_sop:
    - if one or more SOPs were matched: next action should be generate_sop_code (choose the highest-score SOP that has NOT been executed yet; never run the same SOP twice).
    - if no SOP was matched (or matches are irrelevant): next action should be generate_sop.
- If last action == generate_sop: next action should be generate_sop_code for the new SOP.
- If last action == generate_sop_code: next action should be run_sop.
- If last action == run_sop:
    - if an error happened: next action should be generate_sop_code (regenerate the correct code with the right parameters).
    - if it succeeded: next action should be match_observation (query = the whole observation without any deletion).
- If last action == match_observation: next action should be match_sop, matching the SOP of the hypothesized anomaly class (go from a general to a more specific SOP).
- If all three parts of the root cause (location, anomaly type, anomaly reason) have been correctly found: next action should be Speak."""


TOOL_DOCS = """# FLOW ACTIONS (each step you choose exactly ONE action):
- match_sop(query): retrieve the most relevant SOPs by name similarity. No LLM.
- generate_sop(fault_info): generate a NEW SOP for a fault that no existing SOP covers.
- generate_sop_code(sop_name): translate a chosen SOP into runnable Python code.
- run_sop(): execute the most recently generated SOP code and return its observation.
- match_observation(observation): analyze an observation to hypothesize the fault type and judge whether the root cause is found.
- Speak: report the final root cause (only after it has been found).

# DATA-ANALYSIS TOOLS AVAILABLE INSIDE SOP CODE
These are not MainAgent actions. They are the only functions callable inside SOP code generated by generate_sop_code.
- whether_is_abnormal_metric(start_time, end_time, kpi_name, component=None): detect anomalies of a metric KPI against a global threshold; returns anomalous component/KPI/time.
- get_relevant_metric(query): list metric KPI names matching a keyword (use this before querying a specific KPI).
- collect_trace(start_time, end_time, service=None): summarize abnormal traces and the most-downstream faulty component.
- get_logs(component, start_time, end_time): error counts and raw error messages for a component (unavailable on some datasets).
- component_analyze(start_time, end_time): rank all candidate components by their anomaly counts.
All time arguments are strings '%Y-%m-%d %H:%M:%S' in the SAME timezone as the incident description; copy them from the instruction, never convert timezones yourself."""


JSON_RETRY_SUFFIX = (
    "Your previous response was not valid JSON. Respond again with ONLY the JSON "
    "object, parseable by json.loads, and no other text, no markdown fences."
)


def _root_cause_definition(candidates: str, reasons: List[str], ask_datetime: bool) -> str:
    reasons_txt = ", ".join(reasons) if reasons else "the dataset's fault-reason vocabulary"
    dt = (
        "\n4. Occurrence datetime: the specific minute when the root cause fault begins, "
        "format '%Y-%m-%d %H:%M:%S', in the timezone of the incident description."
        if ask_datetime else ""
    )
    return f"""## DEFINITION OF ROOT CAUSE
A root cause consists of the following parts; only when all are correctly found is the root cause found:
1. Location: exactly one component chosen from the candidate component list below (a service is the location only if all of its pods are anomalous).
2. Anomaly type: exactly one reason from this closed set: {reasons_txt}. Anything outside this set is not a correct type.
3. Anomaly reason: concrete telemetry evidence (a specific anomalous KPI / log / trace). A bare "metric increased/decreased" is NOT a valid reason.{dt}

{candidates}"""


def main_agent_system(
    objective: str,
    background: str,
    candidates: str,
    reasons: List[str],
    ask_datetime: bool,
) -> str:
    return f"""You are the MainAgent of a multi-agent system performing Root Cause Analysis on a monitored software system. An anomaly has occurred. You orchestrate the localization process by choosing, at each step, ONE action from a proposed action set, following the SOP flow. Other agents assist you: an ActionAgent proposes the action set, a CodeAgent turns SOPs into code, an ObAgent hypothesizes fault types, and a JudgeAgent decides whether the root cause has been found.

The anomaly / task is:
{objective}

There is some domain knowledge about the telemetry for you:
{background}

{_root_cause_definition(candidates, reasons, ask_datetime)}

{FLOW_RULES}

{TOOL_DOCS}

# OTHER RULES
1. Do not judge the anomaly type from a metric name alone (e.g. an RTT anomaly does not by itself mean "network delay").
2. Do not make wild guesses; rely on evidence gathered by running SOP code.
3. Do not call the same tool repeatedly with the same arguments.
4. Choose your action from the proposed action set given at each step. Prefer the action consistent with the SOP flow.

# RESPONSE FORMAT
Respond with a JSON object, parseable by json.loads, and NOTHING else:
{{"analysis": "your reasoning about the last observation and what to do next", "action": "one action name from the proposed set", "action_input": "the argument for that action: a query / fault description / SOP name / observation string for a flow action. Use an empty string if not needed."}}"""


def main_agent_user(history: str, action_set_text: str, step: int) -> str:
    return f"""# DIAGNOSIS HISTORY (step {step})
{history if history else "(empty - this is the first step)"}

# PROPOSED ACTION SET (choose exactly one 'action')
{action_set_text}

Based on the history and the SOP flow, choose the single best next action. Respond in the required JSON format only."""


def action_agent_prompt(history: str, executed_calls: List[str], n: int) -> str:
    executed = "\n".join(f"- {c}" for c in executed_calls) if executed_calls else "(none yet)"
    return f"""You are the ActionAgent. Based on the diagnosis history below, propose {n} reasonable next actions for the MainAgent to choose from, following the SOP flow.

# DIAGNOSIS HISTORY
{history if history else "(empty - this is the first step)"}

{FLOW_RULES}

{TOOL_DOCS}

# ALREADY-EXECUTED CALLS (do not propose repeating these with the same arguments)
{executed}

# RULES FOR SUGGESTING ACTIONS
1. If the last action is run_sop and an error happened, suggest generate_sop_code to regenerate correct code with correct parameters.
2. If the last action is match_sop and no reasonable SOP was found, suggest generate_sop to generate a new SOP.
3. If the last action is match_sop and a matched SOP was found, suggest generate_sop_code to generate its code.
4. If the last action is match_observation and the anomaly type is uncertain, suggest match_sop for a more specific SOP.
5. If the last action is generate_sop and you got a new SOP, suggest generate_sop_code then run_sop.
6. Try to use as many different tools as possible; do not repeat the same tool with the same argument.
7. Do not guess service names or metric names.
8. If a SOP was already executed successfully, do not execute it again in a short period.

# RESPONSE FORMAT
Respond with a JSON object of exactly {n} entries mapping an action name (one of: {", ".join(ALL_ACTIONS)}) to a short reason (<= 20 words), parseable by json.loads, and nothing else. Example:
{{"match_sop": "start by matching a SOP to the fault", "component_analyze": "quick macro overview of anomalous components"}}
Only use the action names listed above as keys."""


def judge_agent_prompt(history: str, candidates: str, reasons: List[str], ask_datetime: bool) -> str:
    return f"""Currently, an anomaly happened in a monitored system. The following is the diagnosis history between the agents:

``````History Begin``````
{history}
``````History End``````

{_root_cause_definition(candidates, reasons, ask_datetime)}

# TASK
Judge whether the root cause has been found correctly and completely from the history above. Answer "Yes" only if the location, the anomaly type, and the anomaly reason{" and the occurrence datetime" if ask_datetime else ""} are all pinned down with evidence. If the task states there are multiple independent failures, answer "Yes" only when all of them are identified.

Respond with a JSON string parseable by json.loads with exactly two keys and no other words:
{{"judgement": "Yes" or "No", "analysis": "brief justification; if Yes, state the located component(s), type(s), reason(s)"}}"""


def ob_agent_prompt(observation: str, reasons: List[str]) -> str:
    reasons_txt = ", ".join(reasons) if reasons else "(no closed vocabulary provided)"
    return f"""Below is a new observation from the root cause analysis of a monitored system.

``````Observation Begin``````
{observation}
``````Observation End``````

The closed set of possible fault types for this system is: {reasons_txt}.

Decide which fault type this observation most likely indicates, or state that it is uncertain. Rules you must follow:
- Do NOT infer the type from a KPI/trace name alone. A KPI named "rtt"/"latency" being anomalous does not by itself mean "network latency", and a memory-named KPI moving does not by itself mean a memory fault. Judge from the actual evidence: which KPI, the DIRECTION and magnitude of the change, plus logs and traces.
- Mind the direction: packet loss / retransmission usually appear as retransmit RISES together with throughput or success-rate DROPS, not as latency rises. High CPU/memory/disk appear as resource-usage RISES.
- If the observation does not clearly point to a single type, answer "uncertain" and state exactly what additional check would disambiguate it (e.g. which KPI to inspect with whether_is_abnormal_metric, or a collect_trace on the call chain).

Give the type (or "uncertain") and a short analysis (no more than 100 words). For example:
"The fault class is likely to be ... because ..."
"The fault class is uncertain; to disambiguate, check ... with whether_is_abnormal_metric."""


def code_agent_prompt(history: str, sop_name: str, sop_text: str, window_hint: Optional[tuple] = None) -> str:
    if window_hint and window_hint[0] and window_hint[1]:
        window_block = (
            "# INCIDENT WINDOW FOR THIS TASK (use these EXACT strings for start_time / end_time)\n"
            f"start_time = '{window_hint[0]}'\n"
            f"end_time = '{window_hint[1]}'\n"
            "These are the real times for this incident. The timestamps in the example further "
            "below are ONLY a format illustration — never copy them; always use the two values above."
        )
    else:
        window_block = (
            "# INCIDENT WINDOW FOR THIS TASK\n"
            "Copy start_time and end_time verbatim from the incident description in the history above. "
            "The timestamps in the example below are ONLY a format illustration — never copy them."
        )
    return f"""Currently, a user is diagnosing a fault and interacting with the assistant. The following is the diagnosis history:

``````History Begin``````
{history}
``````History End``````

The assistant wants to translate the following SOP into Python code using generate_sop_code:

SOP Name: {sop_name}
{sop_text}

{window_block}

Translate the SOP above into Python code, following ALL the information you have.

Rules you must obey:
1. Assign start_time and end_time to the exact incident-window strings given above. For kpi_name, pass a concrete keyword taken from the history (e.g. 'cpu', 'memory', 'disk', 'network') or an empty string '' to scan all KPIs. For component, pass a concrete component name from the history or None to scan all candidate components. NEVER write a literal placeholder such as 'kpi_name_placeholder' or 'suspected_component' — if you do not know a name, use '' / None, or first call component_analyze / collect_trace / get_relevant_metric to discover it.
2. Do NOT loop over, split, or index the text returned by a tool — tool outputs are human-readable summaries, not structured data. Call each tool once with concrete arguments; to cover all components at once pass component=None rather than iterating over a result string.
3. Your code must strictly follow the SOP steps in order.
4. The last line of the code must be `answer = ...`.
5. The code must be valid Python.
6. All the tool functions return type str, so build the answer by string concatenation, e.g. `answer = a + ' ' + b`.
7. You may ONLY call these functions (already available, do NOT import anything, do NOT define your own helper functions, do NOT read files):
   whether_is_abnormal_metric(start_time, end_time, kpi_name, component=None), get_relevant_metric(query), collect_trace(start_time, end_time, service=None), get_logs(component, start_time, end_time), component_analyze(start_time, end_time).
8. Time arguments are strings '%Y-%m-%d %H:%M:%S' in the same timezone as the incident description; use the incident-window values above and never convert timezones yourself.

Example (FORMAT ONLY — do not reuse these timestamps):
start_time = '<the incident start_time above>'
end_time = '<the incident end_time above>'
overview = component_analyze(start_time, end_time)
answer = overview

Respond with a JSON string parseable by json.loads with the single key 'code' and no other words:
{{"code": "start_time = '...'\\n...\\nanswer = ..."}}"""


def generate_sop_prompt(fault_info: str, seed_examples: str) -> str:
    return f"""You are generating a new Standard Operating Procedure (SOP) for a Root Cause Analysis system, because no existing SOP matches the current fault.

Here are examples of existing SOPs (use them as a style guide):
{seed_examples}

Write a new SOP for the following fault information:
{fault_info}

The SOP steps may ONLY use these tools: whether_is_abnormal_metric, get_relevant_metric, collect_trace, get_logs, component_analyze. The final step must be "N. The answer is the observations obtained from the former steps."

Respond with a JSON string parseable by json.loads with keys 'name' and 'steps' (a list of numbered step strings), and no other words:
{{"name": "...", "steps": ["1. ...", "2. ...", "3. The answer is the observations obtained from the former steps."]}}"""


# Final-answer template — kept faithful to the RCA-datasets scoring contract:
# the JSON key ORDER (datetime -> component -> reason) and the "only if more than
# one failure" multi-answer conditioning are what evaluate.py depends on.
_SPEAK_FINAL = """{lead} You should now provide the final answer to the issue. The candidates of possible root cause components and reasons are provided to you. The root cause components and reasons must be selected from the provided candidates.

{cand}

Recall the issue is: {objective}

Please first review the diagnosis history to infer an exact answer, then summarize your final answer using the following JSON format at the end of your response:

```json
{{
    "1": {{
        "root cause occurrence datetime": (if asked by the issue, format: '%Y-%m-%d %H:%M:%S', otherwise ommited),
        "root cause component": (if asked by the issue, one selected from the possible root cause component list, otherwise ommited),
        "root cause reason": (if asked by the issue, one selected from the possible root cause reason list, otherwise ommited)
    }}, (mandatory)
    "2": {{
        "root cause occurrence datetime": (...),
        "root cause component": (...),
        "root cause reason": (...)
    }} (only if the failure number is "unknown" or "more than one" in the issue)
}}
```
(Use "```json" and "```" tags to wrap the JSON object. Only provide the elements asked by the issue and omit the others.)
Note that all the root cause components and reasons must be selected from the provided candidates. Do not reply 'unknown' or 'null' or 'not found'. Be decisive and infer a possible answer based on the diagnosis history."""


def speak_final(objective: str, candidates: str, forced: bool) -> str:
    lead = (
        "Now, the maximum steps of your reasoning have been reached."
        if forced
        else "Now, you have decided to finish your reasoning process."
    )
    return _SPEAK_FINAL.format(lead=lead, cand=candidates, objective=objective)
